# Generated by Django 5.2.17 on 2026-08-11 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_document_education_level_document_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='education_level',
            field=models.CharField(choices=[('umum', 'Umum/Perguruan Tinggi'), ('sd', 'SD'), ('smp', 'SMP'), ('sma', 'SMA'), ('pt', 'Perguruan Tinggi')], default='umum', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='grade',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
