# Generated by Django 5.2.17 on 2026-08-11 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_profile_education_level_profile_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='preferences_set',
            field=models.BooleanField(default=False),
        ),
    ]
