# Generated by Django 5.2.17 on 2026-08-11 13:30

from django.db import migrations


def set_existing_preferences(apps, schema_editor):
    Profile = apps.get_model('core', 'Profile')
    Profile.objects.filter(preferences_set=False).update(preferences_set=True)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_profile_preferences_set'),
    ]

    operations = [
        migrations.RunPython(set_existing_preferences, migrations.RunPython.noop),
    ]
