# Generated by Django 5.2.17 on 2026-08-12 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_set_existing_profiles_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='summary_html',
            field=models.TextField(blank=True, default=''),
        ),
    ]
