# Generated by Django 5.2.17 on 2026-08-18 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_practicesession'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='language',
            field=models.CharField(choices=[('id', 'Bahasa Indonesia'), ('en', 'English'), ('ar', 'العربية'), ('ms', 'Bahasa Melayu')], default='id', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='language',
            field=models.CharField(choices=[('id', 'Bahasa Indonesia'), ('en', 'English'), ('ar', 'العربية'), ('ms', 'Bahasa Melayu')], default='id', max_length=10),
        ),
        migrations.AlterField(
            model_name='document',
            name='education_level',
            field=models.CharField(choices=[('umum', 'Umum'), ('sd', 'SD'), ('smp', 'SMP'), ('sma', 'SMA'), ('pt', 'Perguruan Tinggi')], default='umum', max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='education_level',
            field=models.CharField(choices=[('umum', 'Umum'), ('sd', 'SD'), ('smp', 'SMP'), ('sma', 'SMA'), ('pt', 'Perguruan Tinggi')], default='umum', max_length=10),
        ),
    ]
